#pydantic
"""
Models - Core Data Structures
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


# ============================================================
# Enums
# ============================================================

class IncidentSeverity(str, Enum):
    LOW      = "low"
    MEDIUM   = "medium"
    HIGH     = "high"
    CRITICAL = "critical"


class IncidentStatus(str, Enum):
    DETECTED      = "detected"       # MonitoringAgent spotted the anomaly
    INVESTIGATING = "investigating"  # KnowledgeAgent is analyzing
    REMEDIATING   = "remediating"    # SelfHealingAgent is applying a fix
    RESOLVED      = "resolved"       # System confirmed recovery
    FAILED        = "failed"         # Remediation attempted but failed
    ESCALATED     = "escalated"      # Needs human intervention


class RemediationAction(str, Enum):
    RESTART_SERVICE     = "restart_service"
    ROLLBACK_DEPLOYMENT = "rollback_deployment"
    SCALE_SERVICE       = "scale_service"
    RESTART_CONTAINER   = "restart_container"
    CUSTOM              = "custom"


# ============================================================
# Incident - The core model of the system
# ============================================================

@dataclass
class Incident:
    """
    Represents a detected problem in the infrastructure.
    Created by the MonitoringAgent and passed through the workflow.

    Example:
        Incident(
            service="auth-api",
            severity=IncidentSeverity.HIGH,
            description="Error rate spiked to 45%",
            metrics={"error_rate": 0.45, "cpu": 0.91},
            logs=["ERROR: connection timeout", "ERROR: OOM killed"]
        )
    """
    service: str
    severity: IncidentSeverity
    description: str

    # Raw data from MonitoringAgent
    metrics: Dict[str, Any] = field(default_factory=dict)
    logs: List[str] = field(default_factory=list)

    # Auto-generated
    incident_id: str = field(default_factory=lambda: f"INC-{str(uuid.uuid4())[:8].upper()}")
    status: IncidentStatus = IncidentStatus.DETECTED
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"Incident(id={self.incident_id}, "
            f"service={self.service}, "
            f"severity={self.severity}, "
            f"status={self.status})"
        )


# ============================================================
# Solution - Output from the KnowledgeAgent
# ============================================================

@dataclass
class Solution:
    """
    The recommendation generated by the KnowledgeAgent (RAG + LLM).
    Passed to the SelfHealingAgent for execution.

    Example:
        Solution(
            incident_id="INC-ABC123",
            root_cause="Memory leak in auth-service",
            recommended_action=RemediationAction.RESTART_SERVICE,
            confidence=0.87,
            explanation="Service memory usage reached 98%..."
        )
    """
    incident_id: str
    root_cause: str
    recommended_action: RemediationAction
    confidence: float                         # 0.0 -> 1.0
    explanation: str                          # Human-readable reasoning
    raw_llm_response: Optional[str] = None   # Full LLM output for debugging
    retrieved_docs: List[str] = field(default_factory=list)  # RAG sources used
    created_at: datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"Solution(incident={self.incident_id}, "
            f"action={self.recommended_action}, "
            f"confidence={self.confidence:.0%})"
        )


# ============================================================
# RemediationResult - Output from the SelfHealingAgent
# ============================================================

@dataclass
class RemediationResult:
    """
    The result of a remediation attempt by the SelfHealingAgent.

    Example:
        RemediationResult(
            incident_id="INC-ABC123",
            action=RemediationAction.RESTART_SERVICE,
            success=True,
            output="kubectl rollout restart deployment/auth-api"
        )
    """
    incident_id: str
    action: RemediationAction
    success: bool
    output: str                              # Command output or error message
    executed_at: datetime = field(default_factory=datetime.utcnow)
    verified: bool = False                   # Did MonitoringAgent confirm recovery?

    def __str__(self):
        status = "SUCCESS" if self.success else "FAILED"
        return (
            f"RemediationResult(incident={self.incident_id}, "
            f"action={self.action}, "
            f"status={status})"
        )


# ============================================================
# Alert - Output from the AlertingAgent
# ============================================================

@dataclass
class Alert:
    """
    A notification sent to engineers via Slack, Email, etc.

    Example:
        Alert(
            incident_id="INC-ABC123",
            title="Incident Resolved: auth-api",
            message="Service recovered after restart.",
            channel="slack"
        )
    """
    incident_id: str
    title: str
    message: str
    channel: str                             # slack | email | webhook
    severity: IncidentSeverity = IncidentSeverity.MEDIUM
    sent_at: datetime = field(default_factory=datetime.utcnow)
    delivered: bool = False

    def __str__(self):
        return (
            f"Alert(incident={self.incident_id}, "
            f"channel={self.channel}, "
            f"delivered={self.delivered})"
        )


# ============================================================
# DeploymentRecord - Output from the CICDAgent
# ============================================================

@dataclass
class DeploymentRecord:
    """
    Tracks a deployment triggered by the CICDAgent.

    Example:
        DeploymentRecord(
            service="auth-service",
            branch="main",
            triggered_by="cicd_agent"
        )
    """
    service: str
    branch: str
    triggered_by: str                        # Agent name or "manual"
    deployment_id: str = field(default_factory=lambda: f"DEP-{str(uuid.uuid4())[:8].upper()}")
    success: Optional[bool] = None           # None = in progress
    started_at: datetime = field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    logs: List[str] = field(default_factory=list)

    def __str__(self):
        return (
            f"DeploymentRecord(id={self.deployment_id}, "
            f"service={self.service}, "
            f"branch={self.branch})"
        )