#pydantic
"""
core/models.py
--------------
Core data models used across all agents in the system.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


# ============================================================
# Enums
# ============================================================

class Severity(str, Enum):
    LOW      = "low"
    MEDIUM   = "medium"
    HIGH     = "high"
    CRITICAL = "critical"


class IncidentStatus(str, Enum):
    OPEN          = "open"
    INVESTIGATING = "investigating"
    REMEDIATING   = "remediating"
    RESOLVED      = "resolved"
    FAILED        = "failed"


class AgentStatus(str, Enum):
    IDLE    = "idle"
    RUNNING = "running"
    STOPPED = "stopped"
    ERROR   = "error"


class DeploymentStatus(str, Enum):
    PENDING     = "pending"
    RUNNING     = "running"
    SUCCESS     = "success"
    FAILED      = "failed"
    ROLLED_BACK = "rolled_back"


class RemediationStatus(str, Enum):
    PENDING  = "pending"
    APPROVED = "approved"
    RUNNING  = "running"
    SUCCESS  = "success"
    FAILED   = "failed"
    REJECTED = "rejected"

class VerificationStatus(str, Enum):
    PASS    = "PASS"
    FAIL    = "FAIL"
    UNKNOWN = "UNKNOWN"     # LLM could not determine from outputs
# ============================================================
# Core Models
# ============================================================

@dataclass
class Metric:
    """A single metric reading from the Monitoring Agent."""
    name: str
    value: float
    unit: str
    service: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    labels: Dict[str, str] = field(default_factory=dict)

    def __str__(self):
        return f"Metric({self.name}={self.value}{self.unit}, service={self.service})"


@dataclass
class Log:
    """A single log entry from the Monitoring Agent."""
    message: str
    level: str
    service: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self):
        return f"Log({self.level}: {self.message[:60]}...)"


@dataclass
class Incident:
    """
    An Incident is created by the Monitoring Agent
    and passed to the Knowledge Agent for investigation.

    Example:
        Incident(
            service="auth-api",
            severity=Severity.HIGH,
            description="API error rate > 40%"
        )
    """
    service: str
    severity: Severity
    description: str
    incident_id: str = field(default_factory=lambda: f"INC-{str(uuid.uuid4())[:8].upper()}")
    status: IncidentStatus = IncidentStatus.OPEN
    metrics: List[Metric] = field(default_factory=list)
    logs: List[Log] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self):
        return (
            f"Incident(id={self.incident_id}, "
            f"service={self.service}, "
            f"severity={self.severity.value}, "
            f"status={self.status.value})"
        )


@dataclass
class Solution:
    """
    Generated by the Knowledge Agent after RAG investigation.
    Passed to the Self-Healing Agent for execution.
    """
    incident_id: str
    root_cause: str
    healing_prompt: str
    confidence: float
    suggested_commands: List[str] = field(default_factory=list)
    references: List[str] = field(default_factory=list)
    source: str = "knowledge_base"
    created_at: datetime = field(default_factory=datetime.utcnow)
     # ── NEW FIELDS ──────────────────────────────────────
    files_to_modify: List[Dict] = field(default_factory=list)
        # Each entry:  {"path": str, "action": str, "content": str}
        # action = "replace_line" | "append" | "overwrite"
        
    def __str__(self):
        return (
            f"Solution(incident={self.incident_id}, "
            f"confidence={self.confidence:.2f}, "
            f"source={self.source})"
        )

@dataclass
class LLMFixResponse:
    """
    Response from the LLM Fixer Agent after analyzing a Solution
    and applying file-level modifications.

    Example:
        LLMFixResponse(
            incident_id="INC-001",
            modified_files=[{"path": "deploy.yaml", "new_content": "..."}],
            steps=["Identified misconfigured replica count", "Updated replicas to 3"],
            confidence=0.91
        )
    """
    incident_id: str
    modified_files: List[Dict]
    # Each entry: {"path": str, "new_content": str, "action": str}

    steps: List[str]
    confidence: float
    remediation_commands: List[Dict]    = field(default_factory=list)
    raw_response: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"LLMFixResponse(incident={self.incident_id}, "
            f"files={len(self.modified_files)}, "
            f"confidence={self.confidence:.2f})"
        )

@dataclass
class FileModificationResult:
    """
    Holds the before/after state of a single file touched by the fixer.

    Example:
        FileModificationResult(
            path="k8s/deployment.yaml",
            old_content="replicas: 1\n...",
            new_content="replicas: 3\n...",
            action="overwrite",
            applied=True,
        )
    """
    path: str
    old_content: str           # content read from disk BEFORE the fix
    new_content: str           # content produced by the LLM
    action: str                # overwrite | append | replace_line
    applied: bool = False      # True once written to disk
    backup_path: Optional[str] = None   
    error: Optional[str] = None

    def __str__(self):
        status = "applied" if self.applied else ("error" if self.error else "pending")
        return (
            f"FileModificationResult("
            f"path={self.path}, "
            f"action={self.action}, "
            f"backup={self.backup_path}, "
            f"status={status})"
        )

@dataclass
class CommandExecutionResult:
    """
    Outcome of a single remediation command executed after file changes.
 
    Example:
        CommandExecutionResult(
            command="systemctl restart nginx",
            description="Reload nginx after config update",
            order=1,
            on_failure="abort",
            returncode=0,
            stdout="",
            stderr="",
        )
    """
    command: str
    description: str
    order: int
    on_failure: str                     # "abort" | "continue" | "retry"
    returncode: Optional[int] = None    # None if not yet run / skipped
    stdout: str = ""
    stderr: str = ""
    skipped: bool = False               # True if an earlier abort stopped execution
    error: Optional[str] = None         # Python-level exception message, if any
 
    @property
    def succeeded(self) -> bool:
        return self.returncode == 0
 
    def __str__(self):
        if self.skipped:
            state = "skipped"
        elif self.error:
            state = f"error({self.error})"
        elif self.returncode is None:
            state = "pending"
        else:
            state = "ok" if self.succeeded else f"failed(rc={self.returncode})"
        return (
            f"CommandExecutionResult("
            f"order={self.order}, "
            f"cmd={self.command!r}, "
            f"state={state})"
        )
    

@dataclass
class CommandResult:
    """
    Result of a single verification command execution.

    Example:
        CommandResult(
            command="pip check",
            exit_code=0,
            stdout="No broken requirements found.",
            stderr="",
            passed=True,
        )
    """
    command:   str
    exit_code: int
    stdout:    str
    stderr:    str
    passed:    bool            # exit_code == 0
    error:     Optional[str] = None   # set if subprocess itself failed

    def __str__(self):
        status = "✓" if self.passed else "✗"
        return (
            f"CommandResult({status} exit={self.exit_code}, "
            f"cmd={self.command[:60]})"
        )

@dataclass
class VerificationReport:
    """
    Final report produced by the LLM Verifier.

    Example:
        VerificationReport(
            incident_id="INC-001",
            status=VerificationStatus.PASS,
            commands_run=["pip check", "python -c 'import httpx'"],
            results=[...],
            reason="All packages resolved. httpx imported successfully.",
            confidence=0.97,
        )
    """
    incident_id:   str
    status:        VerificationStatus
    commands_run:  List[str]
    results:       List[CommandResult]
    reason:        str
    confidence:    float
    raw_response:  Optional[str] = None
    created_at:    datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"VerificationReport("
            f"incident={self.incident_id}, "
            f"status={self.status.value}, "
            f"commands={len(self.commands_run)}, "
            f"confidence={self.confidence:.2f})"
        )

@dataclass
class SelfHealingResult:
    """
    Final result returned by the Self-Healing Agent after processing a Solution.

    Example:
        SelfHealingResult(
            incident_id="INC-001",
            status=RemediationStatus.SUCCESS,
            file_modifications=[...],
            steps=["Updated replicas", "Fixed env var"],
            confidence=0.91,
        )
    """
    incident_id: str
    status: RemediationStatus
    file_modifications: List[FileModificationResult] = field(default_factory=list)
    steps: List[str] = field(default_factory=list)
    confidence: float = 0.0
    validation_errors: List[str] = field(default_factory=list)
    remediation_command_results: List[CommandExecutionResult] = field(default_factory=list)
    llm_response: Optional[LLMFixResponse] = None
    verification: Optional[VerificationReport] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        ver = self.verification.status.value if self.verification else "not_run"
        cmd_ok  = sum(1 for c in self.remediation_command_results if c.succeeded)
        cmd_tot = len(self.remediation_command_results)
        return (
            f"SelfHealingResult("
            f"incident={self.incident_id}, "
            f"status={self.status.value}, "
            f"files={len(self.file_modifications)}, "
            f"cmds={cmd_ok}/{cmd_tot}, "
            f"verification={ver}, "
            f"confidence={self.confidence:.2f})"
        )




@dataclass
class RemediationAction:
    """
    A single remediation action executed by the Self-Healing Agent.

    Example:
        RemediationAction(
            incident_id="INC-001",
            command="kubectl rollout restart deployment/auth-api",
            description="Restart auth-api deployment"
        )
    """
    incident_id: str
    command: str
    description: str
    action_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    status: RemediationStatus = RemediationStatus.PENDING
    output: Optional[str] = None
    error: Optional[str] = None
    executed_at: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"RemediationAction(id={self.action_id}, "
            f"status={self.status.value}, "
            f"cmd={self.command[:50]})"
        )


@dataclass
class Alert:
    """
    Sent by the Alerting Agent to notify engineers.
    """
    incident_id: str
    title: str
    message: str
    severity: Severity
    channel: str
    alert_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    sent: bool = False
    sent_at: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"Alert(id={self.alert_id}, "
            f"severity={self.severity.value}, "
            f"channel={self.channel})"
        )


@dataclass
class Deployment:
    """
    Tracks a deployment triggered by the CI/CD Agent.
    """
    service: str
    branch: str
    version: str
    deployment_id: str = field(default_factory=lambda: f"DEP-{str(uuid.uuid4())[:8].upper()}")
    status: DeploymentStatus = DeploymentStatus.PENDING
    pipeline_url: Optional[str] = None
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self):
        return (
            f"Deployment(id={self.deployment_id}, "
            f"service={self.service}, "
            f"status={self.status.value})"
        )